In [6]:
import numpy
print(numpy.__version__)


2.4.2


In [1]:
import numpy as np

In [2]:
arr=np.array([1500,3000,5000])

In [ ]:
daily_sales=np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

In [4]:
print(arr.shape)

(3,)


In [5]:
print(daily_sales.shape)

(3, 4)


In [9]:
Grace_unit=np.array(daily_sales + 2)

In [10]:
print(Grace_unit)

[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


In [12]:
Multi= np.dot(arr,daily_sales)

In [13]:
print(Multi)

[40000 58500 34000 56000]


In [14]:
np.sqrt(daily_sales)

array([[3.16227766, 3.87298335, 2.82842712, 3.46410162],
       [2.23606798, 2.64575131, 2.        , 2.44948974],
       [1.41421356, 1.73205081, 1.41421356, 2.        ]])

In [18]:
smartwatch_sales = daily_sales[0]
print(smartwatch_sales)


[10 15  8 12]


In [17]:
speakers_thursday_sales = daily_sales[2][3]
print(speakers_thursday_sales)


4


In [19]:
subarray = daily_sales[0:2, 0:2]
print(subarray)


[[10 15]
 [ 5  7]]


In [20]:
flat_sales = daily_sales.reshape(-1)
print(flat_sales)


[10 15  8 12  5  7  4  6  2  3  2  4]


In [21]:
sales_2x6 = daily_sales.reshape(2, 6)
print(sales_2x6)


[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]


In [22]:
discount = np.linspace(0, 100, 10)
print(discount)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [23]:
predicted_sales = np.random.randint(0, 21, size=(3, 4))
print(predicted_sales)

[[16 14 20  9]
 [12 14 12 14]
 [ 2  1  6  5]]


In [25]:
random_values = np.random.rand(5)
print(random_values)


[0.69178078 0.1005427  0.37442894 0.50704342 0.53522929]


In [26]:
total_items_sold = np.sum(daily_sales)
print(total_items_sold)


78


In [27]:
total_per_product = np.sum(daily_sales, axis=1)
print(total_per_product)


[45 22 11]
