In [ ]:
import numpy as np

In [ ]:
arr=np.random.randint(120,650,size=(4,7))
print(arr)

[[134 346 385 527 135 472 468]
 [495 288 218 435 151 354 619]
 [286 577 569 196 520 609 381]
 [237 271 232 479 136 438 129]]


In [ ]:
print(arr.shape)

(4, 7)


In [ ]:
print(arr.ndim)

2


In [ ]:
print(arr.size)

28


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
avg=np.mean(arr)
print(avg)

360.25


In [ ]:
avg_per_hostel=np.mean(arr,axis=1)
print(avg_per_hostel)

[352.42857143 365.71428571 448.28571429 274.57142857]


In [ ]:
max_value = np.max(arr)
print(max_value)

619


In [ ]:
max_per_hostel = np.max(arr, axis=1)
print(max_per_hostel)

[527 619 609 479]


In [ ]:
total_per_hostel = np.sum(arr, axis=1)
print(total_per_hostel)

highest_hostel = np.argmax(total_per_hostel)
print( highest_hostel)


[2467 2560 3138 1922]
2


In [ ]:
total_per_day = np.sum(arr, axis=0)
print(total_per_day)


[1152 1482 1404 1637  942 1873 1597]


In [ ]:
highest_day_index = np.argmax(total_per_day)
print( highest_day_index)


5


In [ ]:
penalized_usage = np.where(arr > 550, arr * 1.20, arr)
print(penalized_usage)


[[134.  346.  385.  527.  135.  472.  468. ]
 [495.  288.  218.  435.  151.  354.  742.8]
 [286.  692.4 682.8 196.  520.  730.8 381. ]
 [237.  271.  232.  479.  136.  438.  129. ]]


In [ ]:
boolean_matrix = arr > avg_per_hostel[:, np.newaxis]
print(boolean_matrix)


[[False False  True  True False  True  True]
 [ True False False  True False False  True]
 [False  True  True False  True  True False]
 [False False False  True False  True False]]


In [ ]:
single_row=arr.reshape(1,28)
print(single_row)

[[134 346 385 527 135 472 468 495 288 218 435 151 354 619 286 577 569 196
  520 609 381 237 271 232 479 136 438 129]]


In [ ]:
two_row=arr.reshape(2,14)
print(two_row)

[[134 346 385 527 135 472 468 495 288 218 435 151 354 619]
 [286 577 569 196 520 609 381 237 271 232 479 136 438 129]]


In [ ]:
ref_backup=arr

In [ ]:
safe_backup=arr.copy()

In [ ]:
arr[0][0]=999

In [ ]:
print(ref_backup)

print(safe_backup)

print(arr)

[[999 346 385 527 135 472 468]
 [495 288 218 435 151 354 619]
 [286 577 569 196 520 609 381]
 [237 271 232 479 136 438 129]]
[[134 346 385 527 135 472 468]
 [495 288 218 435 151 354 619]
 [286 577 569 196 520 609 381]
 [237 271 232 479 136 438 129]]
[[999 346 385 527 135 472 468]
 [495 288 218 435 151 354 619]
 [286 577 569 196 520 609 381]
 [237 271 232 479 136 438 129]]
