In [ ]:
import numpy as np

In [ ]:
marks=np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])

In [ ]:
print(marks)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [ ]:
print(marks.shape)

(5, 3)


In [ ]:
print(marks.size)

15


In [ ]:
print(type(marks))

<class 'numpy.ndarray'>


In [ ]:
second_student_marks = marks[1]
print(second_student_marks)


[45 60 55]


In [ ]:
third_subject_marks = marks[:, 2]
print(third_subject_marks)


[90 55 95 35 75]


In [ ]:
student1_marks=marks[1][1]
print(student1_marks)

60


In [ ]:
avg_per_student = np.mean(marks, axis=1)
print(avg_per_student)


[84.33333333 53.33333333 91.66666667 35.         70.        ]


In [ ]:
avg_per_subject=np.mean(marks,axis=0)
print(avg_per_subject)

[61.2 69.4 70. ]


In [ ]:
students_above_80 = marks[avg_per_student >= 80]
print(students_above_80)


[[78 85 90]
 [88 92 95]]


In [ ]:
updated_marks=marks+5
print(updated_marks)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]


In [ ]:
status = np.where(marks > 50, 1, 0)
print(status)


[[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]


In [ ]:
new_marks=np.where(marks < 40,0,marks)
print(new_marks)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [ 0 40  0]
 [65 70 75]]


In [ ]:
grade_score = np.where(avg_per_student >= 85, 10,
               np.where(avg_per_student >= 70, 8,
               np.where(avg_per_student >= 50, 6, 0)))

print(grade_score)


[ 8  6 10  0  8]


In [ ]:
backup=marks.copy()

In [ ]:
marks[0][0]=0

In [ ]:
print(marks)

[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [ ]:
print(backup)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
