In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Range of Numbers

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

Evenly Spaced Numbers

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Array properties

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])

In [ ]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


Type conversion

In [ ]:
arr=np.array([1.2,2.5,3.7])
arr_int=arr.astype(int)
print(arr_int)

[1 2 3]


Indexing & Slicing

In [ ]:
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40


1D Slicing

In [ ]:
print(arr[1:3])
print(arr[:2])
print(arr[::2])

[20 30]
[10 20]
[10 30]


2D Indexing

In [ ]:
mat=np.array([[1,2,3],[4,5,6],[9,7,8]])
print(mat[0,1])
print(mat[1])

2
[4 5 6]


In [ ]:
print(mat[:,1])

[2 5 7]


In [ ]:
a=np.array([1,2,3])
b=a.copy()
b[0]=99
print(a)
print(b)

[1 2 3]
[99  2  3]


Basic Array Operations(Vector Power)

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Scalar operation

In [ ]:
print(a + 10)
print(b * 2)

[11 12 13]
[ 8 10 12]


Unfus(Universal Function)

In [ ]:
arr=np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
7.5
30
5.678908345800274


Boolean Indexing

In [ ]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [ ]:
print(arr>25)

[False False  True  True  True]


Broadcasting Rule

In [ ]:
arr=np.array([1,2,3,4])
print(arr + 10)

[11 12 13 14]


In [ ]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat + 10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
row=np.array([1,2,3])
print(mat+row)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


Matrix Multuiplication

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [ ]:
print(A.T)#transpose

[[1 3]
 [2 4]]


Random Module

In [ ]:
np.random.rand(5)



array([0.78151888, 0.015094  , 0.94114273, 0.33133808, 0.26999116])

In [ ]:
np.random.rand(3,3)

array([[0.70460065, 0.11164933, 0.44325255],
       [0.88398128, 0.7151361 , 0.0774248 ],
       [0.78621308, 0.82057447, 0.07417144]])

In [ ]:
np.random.randint(1,100,10)

array([96, 27, 66, 40, 33, 53, 13, 42, 28, 24])

Reshaping Array

In [ ]:
arr=np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Axis in Numpy

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(np.sum(arr))

21


In [ ]:
print(np.sum(arr,axis=0))

[5 7 9]


In [ ]:
print(np.sum(arr,axis=1))

[ 6 15]


Where in Numpy

In [ ]:
arr=np.array([10,-5,10,-3,15])
result=np.where(arr < 0,0,arr)

In [ ]:
print(result)

[10  0 10  0 15]


In [ ]:
arr=np.array([1,2,3,4,5])
result=np.where(arr % 2 != 0,-1,arr)
print(result)

[-1  2 -1  4 -1]


In [ ]:
marks=np.array([45,78,32,90,55])
status=np.where(marks>=50, 1, 0)
print(status)

[0 1 0 1 1]


In [ ]:
data=np.array([10,20,30,40,50])
mean_val=np.mean(data)
result=np.where(data > mean_val,mean_val,data)
print(result)

[10. 20. 30. 30. 30.]


Applying where condition in (2d) array

In [ ]:
mat=np.array([[10,60,30],[80,20,90]])

In [ ]:
result=np.where(mat>=50,1,0)
print(result)

[[0 1 0]
 [1 0 1]]
